# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Programmer_calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Programmer_calc(object):
    def setupUi(self, Programmer_calc):
        Programmer_calc.setObjectName("Programmer_calc")
        Programmer_calc.resize(884, 856)
        Programmer_calc.setStyleSheet("        QMainWindow {\n"
"            background-color: #2E2E2E;\n"
"        }")
        Programmer_calc.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(Programmer_calc)
        self.centralwidget.setStyleSheet("        QWidget#centralwidget {\n"
"            background-color: #2E2E2E;\n"
"        }")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.operations_list = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operations_list.sizePolicy().hasHeightForWidth())
        self.operations_list.setSizePolicy(sizePolicy)
        self.operations_list.setStyleSheet("        QListWidget{\n"
"            background-color: #2E2E2E;\n"
"            color: #ffffff;\n"
"            font: 14pt;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 5px;\n"
"        }")
        self.operations_list.setObjectName("operations_list")
        self.horizontalLayout.addWidget(self.operations_list)
        self.operations_list2 = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operations_list2.sizePolicy().hasHeightForWidth())
        self.operations_list2.setSizePolicy(sizePolicy)
        self.operations_list2.setStyleSheet("        QListWidget{\n"
"            background-color: #2E2E2E;\n"
"            color: #ffffff;\n"
"            font: 14pt;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 5px;\n"
"        }")
        self.operations_list2.setObjectName("operations_list2")
        self.horizontalLayout.addWidget(self.operations_list2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Result = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Result.sizePolicy().hasHeightForWidth())
        self.Result.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Result.setFont(font)
        self.Result.setStyleSheet("\n"
"            background-color: #4E4E4E;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 5px;\n"
"            padding: 5px;")
        self.Result.setObjectName("Result")
        self.verticalLayout_2.addWidget(self.Result)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("        QComboBox {\n"
"            background-color: #4E4E4E;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 5px;\n"
"            padding: 5px;\n"
"        }\n"
"        QComboBox QAbstractItemView {\n"
"            background-color: #4E4E4E;\n"
"            selection-background-color: #5E5E5E;\n"
"            color: #FFFFFF;\n"
"        }")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_3)
        spacerItem = QtWidgets.QSpacerItem(580, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setStyleSheet("        QLabel{\n"
"            font-size: 14pt;\n"
"            qproperty-alignment: \'AlignRight | AlignTrailing | AlignVCenter\';\n"
"        }")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.n8_63 = QtWidgets.QLabel(self.centralwidget)
        self.n8_63.setStyleSheet("        QLabel {\n"
"            color: #FFFFFF;\n"
"            font-family: \'Courier New\', Courier, monospace; /* Monospaced font */\n"
"            font-size: 16pt; /* Increase font size */\n"
"            padding: 10px; /* Add padding */\n"
"            qproperty-alignment: \'AlignCenter\'; /* Center align */\n"
"        }")
        self.n8_63.setText("")
        self.n8_63.setObjectName("n8_63")
        self.verticalLayout.addWidget(self.n8_63)
        self.t6_31 = QtWidgets.QLabel(self.centralwidget)
        self.t6_31.setStyleSheet("        QLabel {\n"
"            color: #FFFFFF;\n"
"            font-family: \'Courier New\', Courier, monospace; /* Monospaced font */\n"
"            font-size: 16pt; /* Increase font size */\n"
"            padding: 10px; /* Add padding */\n"
"            qproperty-alignment: \'AlignCenter\'; /* Center align */\n"
"        }")
        self.t6_31.setText("")
        self.t6_31.setObjectName("t6_31")
        self.verticalLayout.addWidget(self.t6_31)
        self.h2_47 = QtWidgets.QLabel(self.centralwidget)
        self.h2_47.setStyleSheet("        QLabel {\n"
"            color: #FFFFFF;\n"
"            font-family: \'Courier New\', Courier, monospace; /* Monospaced font */\n"
"            font-size: 16pt; /* Increase font size */\n"
"            padding: 10px; /* Add padding */\n"
"            qproperty-alignment: \'AlignCenter\'; /* Center align */\n"
"        }")
        self.h2_47.setText("")
        self.h2_47.setObjectName("h2_47")
        self.verticalLayout.addWidget(self.h2_47)
        self.nulla_15 = QtWidgets.QLabel(self.centralwidget)
        self.nulla_15.setStyleSheet("        QLabel {\n"
"            color: #FFFFFF;\n"
"            font-family: \'Courier New\', Courier, monospace; /* Monospaced font */\n"
"            font-size: 16pt; /* Increase font size */\n"
"            padding: 10px; /* Add padding */\n"
"            qproperty-alignment: \'AlignCenter\'; /* Center align */\n"
"        }")
        self.nulla_15.setText("")
        self.nulla_15.setObjectName("nulla_15")
        self.verticalLayout.addWidget(self.nulla_15)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_for_numbers = QtWidgets.QGridLayout()
        self.gridLayout_for_numbers.setObjectName("gridLayout_for_numbers")
        self.mod = QtWidgets.QPushButton(self.centralwidget)
        self.mod.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.mod.setObjectName("mod")
        self.gridLayout_for_numbers.addWidget(self.mod, 0, 3, 1, 1)
        self.four = QtWidgets.QPushButton(self.centralwidget)
        self.four.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.four.setObjectName("four")
        self.gridLayout_for_numbers.addWidget(self.four, 4, 0, 1, 1)
        self.bel_zj = QtWidgets.QPushButton(self.centralwidget)
        self.bel_zj.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.bel_zj.setObjectName("bel_zj")
        self.gridLayout_for_numbers.addWidget(self.bel_zj, 0, 1, 1, 1)
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.minus.setObjectName("minus")
        self.gridLayout_for_numbers.addWidget(self.minus, 4, 4, 1, 1)
        self.five = QtWidgets.QPushButton(self.centralwidget)
        self.five.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.five.setObjectName("five")
        self.gridLayout_for_numbers.addWidget(self.five, 4, 1, 1, 1)
        self.jobb_zj = QtWidgets.QPushButton(self.centralwidget)
        self.jobb_zj.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.jobb_zj.setObjectName("jobb_zj")
        self.gridLayout_for_numbers.addWidget(self.jobb_zj, 0, 2, 1, 1)
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        self.zero.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.zero.setObjectName("zero")
        self.gridLayout_for_numbers.addWidget(self.zero, 5, 0, 1, 1)
        self.one = QtWidgets.QPushButton(self.centralwidget)
        self.one.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.one.setObjectName("one")
        self.gridLayout_for_numbers.addWidget(self.one, 5, 1, 1, 1)
        self.B_hex = QtWidgets.QPushButton(self.centralwidget)
        self.B_hex.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.B_hex.setObjectName("B_hex")
        self.gridLayout_for_numbers.addWidget(self.B_hex, 3, 3, 1, 1)
        self.E_hex = QtWidgets.QPushButton(self.centralwidget)
        self.E_hex.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.E_hex.setObjectName("E_hex")
        self.gridLayout_for_numbers.addWidget(self.E_hex, 1, 2, 1, 1)
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        self.eight.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.eight.setObjectName("eight")
        self.gridLayout_for_numbers.addWidget(self.eight, 3, 0, 1, 1)
        self.F_hex = QtWidgets.QPushButton(self.centralwidget)
        self.F_hex.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.F_hex.setObjectName("F_hex")
        self.gridLayout_for_numbers.addWidget(self.F_hex, 1, 3, 1, 1)
        self.pi = QtWidgets.QPushButton(self.centralwidget)
        self.pi.setStyleSheet("\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }")
        self.pi.setObjectName("pi")
        self.gridLayout_for_numbers.addWidget(self.pi, 0, 4, 1, 2)
        self.sqrt = QtWidgets.QPushButton(self.centralwidget)
        self.sqrt.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.sqrt.setObjectName("sqrt")
        self.gridLayout_for_numbers.addWidget(self.sqrt, 1, 5, 1, 1)
        self.dot = QtWidgets.QPushButton(self.centralwidget)
        self.dot.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.dot.setObjectName("dot")
        self.gridLayout_for_numbers.addWidget(self.dot, 3, 5, 1, 1)
        self.seven = QtWidgets.QPushButton(self.centralwidget)
        self.seven.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.seven.setObjectName("seven")
        self.gridLayout_for_numbers.addWidget(self.seven, 4, 3, 1, 1)
        self.divide = QtWidgets.QPushButton(self.centralwidget)
        self.divide.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.divide.setObjectName("divide")
        self.gridLayout_for_numbers.addWidget(self.divide, 1, 4, 1, 1)
        self.equal = QtWidgets.QPushButton(self.centralwidget)
        self.equal.setStyleSheet("        QPushButton#equal {\n"
"            background-color: #ff7300;\n"
"            width: 50px;\n"
"            height: 100%;\n"
"            color: #ffffff;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton#equal:hover {\n"
"            background-color: #fc8e32;\n"
"        }")
        self.equal.setObjectName("equal")
        self.gridLayout_for_numbers.addWidget(self.equal, 4, 5, 2, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.clear.setObjectName("clear")
        self.verticalLayout_4.addWidget(self.clear)
        self.gridLayout_for_numbers.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.A_hex = QtWidgets.QPushButton(self.centralwidget)
        self.A_hex.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.A_hex.setObjectName("A_hex")
        self.gridLayout_for_numbers.addWidget(self.A_hex, 3, 2, 1, 1)
        self.szorzas = QtWidgets.QPushButton(self.centralwidget)
        self.szorzas.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.szorzas.setObjectName("szorzas")
        self.gridLayout_for_numbers.addWidget(self.szorzas, 3, 4, 1, 1)
        self.plusz = QtWidgets.QPushButton(self.centralwidget)
        self.plusz.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.plusz.setObjectName("plusz")
        self.gridLayout_for_numbers.addWidget(self.plusz, 5, 4, 1, 1)
        self.D_hex = QtWidgets.QPushButton(self.centralwidget)
        self.D_hex.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.D_hex.setObjectName("D_hex")
        self.gridLayout_for_numbers.addWidget(self.D_hex, 1, 1, 1, 1)
        self.C_hex = QtWidgets.QPushButton(self.centralwidget)
        self.C_hex.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.C_hex.setObjectName("C_hex")
        self.gridLayout_for_numbers.addWidget(self.C_hex, 1, 0, 1, 1)
        self.two = QtWidgets.QPushButton(self.centralwidget)
        self.two.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.two.setObjectName("two")
        self.gridLayout_for_numbers.addWidget(self.two, 5, 2, 1, 1)
        self.nine = QtWidgets.QPushButton(self.centralwidget)
        self.nine.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.nine.setObjectName("nine")
        self.gridLayout_for_numbers.addWidget(self.nine, 3, 1, 1, 1)
        self.six = QtWidgets.QPushButton(self.centralwidget)
        self.six.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.six.setObjectName("six")
        self.gridLayout_for_numbers.addWidget(self.six, 4, 2, 1, 1)
        self.three = QtWidgets.QPushButton(self.centralwidget)
        self.three.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.three.setObjectName("three")
        self.gridLayout_for_numbers.addWidget(self.three, 5, 3, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_for_numbers)
        self.gridLayout_for_special_buttons = QtWidgets.QGridLayout()
        self.gridLayout_for_special_buttons.setObjectName("gridLayout_for_special_buttons")
        self.aaaa = QtWidgets.QPushButton(self.centralwidget)
        self.aaaa.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.aaaa.setObjectName("aaaa")
        self.gridLayout_for_special_buttons.addWidget(self.aaaa, 3, 3, 1, 2)
        self.OR = QtWidgets.QPushButton(self.centralwidget)
        self.OR.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.OR.setObjectName("OR")
        self.gridLayout_for_special_buttons.addWidget(self.OR, 1, 4, 1, 1)
        self.log = QtWidgets.QPushButton(self.centralwidget)
        self.log.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.log.setObjectName("log")
        self.gridLayout_for_special_buttons.addWidget(self.log, 2, 4, 1, 1)
        self.fakt = QtWidgets.QPushButton(self.centralwidget)
        self.fakt.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.fakt.setObjectName("fakt")
        self.gridLayout_for_special_buttons.addWidget(self.fakt, 3, 0, 1, 1)
        self.int_2 = QtWidgets.QPushButton(self.centralwidget)
        self.int_2.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.int_2.setObjectName("int_2")
        self.gridLayout_for_special_buttons.addWidget(self.int_2, 2, 2, 1, 1)
        self.AND = QtWidgets.QPushButton(self.centralwidget)
        self.AND.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.AND.setObjectName("AND")
        self.gridLayout_for_special_buttons.addWidget(self.AND, 1, 3, 1, 1)
        self.frac = QtWidgets.QPushButton(self.centralwidget)
        self.frac.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.frac.setObjectName("frac")
        self.gridLayout_for_special_buttons.addWidget(self.frac, 3, 2, 1, 1)
        self.log2 = QtWidgets.QPushButton(self.centralwidget)
        self.log2.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.log2.setObjectName("log2")
        self.gridLayout_for_special_buttons.addWidget(self.log2, 2, 3, 1, 1)
        self.twos = QtWidgets.QPushButton(self.centralwidget)
        self.twos.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.twos.setObjectName("twos")
        self.gridLayout_for_special_buttons.addWidget(self.twos, 1, 1, 1, 1)
        self.abs = QtWidgets.QPushButton(self.centralwidget)
        self.abs.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.abs.setObjectName("abs")
        self.gridLayout_for_special_buttons.addWidget(self.abs, 3, 1, 1, 1)
        self.ones = QtWidgets.QPushButton(self.centralwidget)
        self.ones.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.ones.setObjectName("ones")
        self.gridLayout_for_special_buttons.addWidget(self.ones, 1, 0, 1, 1)
        self.x_xx_y = QtWidgets.QPushButton(self.centralwidget)
        self.x_xx_y.setStyleSheet("\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }")
        self.x_xx_y.setObjectName("x_xx_y")
        self.gridLayout_for_special_buttons.addWidget(self.x_xx_y, 2, 0, 1, 1)
        self.XOR = QtWidgets.QPushButton(self.centralwidget)
        self.XOR.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }")
        self.XOR.setObjectName("XOR")
        self.gridLayout_for_special_buttons.addWidget(self.XOR, 0, 4, 1, 1)
        self.fact = QtWidgets.QPushButton(self.centralwidget)
        self.fact.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.fact.setObjectName("fact")
        self.gridLayout_for_special_buttons.addWidget(self.fact, 1, 2, 1, 1)
        self.x_xx_1 = QtWidgets.QPushButton(self.centralwidget)
        self.x_xx_1.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.x_xx_1.setObjectName("x_xx_1")
        self.gridLayout_for_special_buttons.addWidget(self.x_xx_1, 2, 1, 1, 1)
        self.shift_left = QtWidgets.QPushButton(self.centralwidget)
        self.shift_left.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.shift_left.setObjectName("shift_left")
        self.gridLayout_for_special_buttons.addWidget(self.shift_left, 0, 0, 1, 1)
        self.shift_right = QtWidgets.QPushButton(self.centralwidget)
        self.shift_right.setStyleSheet("        QPushButton {\n"
"            background-color: #4E4E4E;\n"
"            font-size: 14pt;\n"
"            width: 50px;\n"
"            height: 50px;\n"
"            color: #FFFFFF;\n"
"            border: 1px solid #555555;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: #5E5E5E;\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: #6E6E6E;\n"
"        }")
        self.shift_right.setObjectName("shift_right")
        self.gridLayout_for_special_buttons.addWidget(self.shift_right, 0, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_for_special_buttons)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_3.setStretch(3, 3)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        Programmer_calc.setCentralWidget(self.centralwidget)

        self.retranslateUi(Programmer_calc)
        QtCore.QMetaObject.connectSlotsByName(Programmer_calc)

    def retranslateUi(self, Programmer_calc):
        _translate = QtCore.QCoreApplication.translate
        Programmer_calc.setWindowTitle(_translate("Programmer_calc", "MainWindow"))
        self.Result.setText(_translate("Programmer_calc", "0"))
        self.comboBox_3.setItemText(0, _translate("Programmer_calc", "Decimal"))
        self.comboBox_3.setItemText(1, _translate("Programmer_calc", "Hexadecimal"))
        self.comboBox_3.setItemText(2, _translate("Programmer_calc", "Binary"))
        self.comboBox_3.setItemText(3, _translate("Programmer_calc", "Octal"))
        self.mod.setText(_translate("Programmer_calc", "mod"))
        self.four.setText(_translate("Programmer_calc", "4"))
        self.bel_zj.setText(_translate("Programmer_calc", "("))
        self.minus.setText(_translate("Programmer_calc", "-"))
        self.five.setText(_translate("Programmer_calc", "5"))
        self.jobb_zj.setText(_translate("Programmer_calc", ")"))
        self.zero.setText(_translate("Programmer_calc", "0"))
        self.one.setText(_translate("Programmer_calc", "1"))
        self.B_hex.setText(_translate("Programmer_calc", "B"))
        self.E_hex.setText(_translate("Programmer_calc", "E"))
        self.eight.setText(_translate("Programmer_calc", "8"))
        self.F_hex.setText(_translate("Programmer_calc", "F"))
        self.pi.setText(_translate("Programmer_calc", "pi"))
        self.sqrt.setText(_translate("Programmer_calc", "sqrt"))
        self.dot.setText(_translate("Programmer_calc", "."))
        self.seven.setText(_translate("Programmer_calc", "7"))
        self.divide.setText(_translate("Programmer_calc", "/"))
        self.equal.setText(_translate("Programmer_calc", "="))
        self.clear.setText(_translate("Programmer_calc", "C"))
        self.A_hex.setText(_translate("Programmer_calc", "A"))
        self.szorzas.setText(_translate("Programmer_calc", "x"))
        self.plusz.setText(_translate("Programmer_calc", "+"))
        self.D_hex.setText(_translate("Programmer_calc", "D"))
        self.C_hex.setText(_translate("Programmer_calc", "C"))
        self.two.setText(_translate("Programmer_calc", "2"))
        self.nine.setText(_translate("Programmer_calc", "9"))
        self.six.setText(_translate("Programmer_calc", "6"))
        self.three.setText(_translate("Programmer_calc", "3"))
        self.aaaa.setText(_translate("Programmer_calc", "aschii"))
        self.OR.setText(_translate("Programmer_calc", "OR"))
        self.log.setText(_translate("Programmer_calc", "log"))
        self.fakt.setText(_translate("Programmer_calc", "x!"))
        self.int_2.setText(_translate("Programmer_calc", "int"))
        self.AND.setText(_translate("Programmer_calc", "AND"))
        self.frac.setText(_translate("Programmer_calc", "frac"))
        self.log2.setText(_translate("Programmer_calc", "log2"))
        self.twos.setText(_translate("Programmer_calc", "twos"))
        self.abs.setText(_translate("Programmer_calc", "|x|"))
        self.ones.setText(_translate("Programmer_calc", "ones"))
        self.x_xx_y.setText(_translate("Programmer_calc", "x^y"))
        self.XOR.setText(_translate("Programmer_calc", "XOR"))
        self.fact.setText(_translate("Programmer_calc", "fact"))
        self.x_xx_1.setText(_translate("Programmer_calc", "x^-1"))
        self.shift_left.setText(_translate("Programmer_calc", "<<"))
        self.shift_right.setText(_translate("Programmer_calc", ">>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Programmer_calc = QtWidgets.QMainWindow()
    ui = Ui_Programmer_calc()
    ui.setupUi(Programmer_calc)
    Programmer_calc.show()
    sys.exit(app.exec_())
